# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Moving Folders

plugins_dir:  _jekyll/plugins
layouts_dir:  _jekyll/layouts
includes_dir: _jekyll/includes
data_dir:     _jekyll/data

# Site settings
title: AMP Project Documentation
description: > # this means to ignore newlines until "baseurl:"
  The official documentation for the AMP Project, including AMP JS,
  AMP HTML and more.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://www.ampproject.org" # the base hostname & protocol for your site
exclude: ["_scripts"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      locale: en

collections:
  get_started: 
    title: Get Started
    output: true
  guides:
    title: Guides
    output: true
  reference:
    title: Reference
    output: true
  support:
    title: Support
    output: true

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _jekyll/sass
